services:
  blog:
    build: .
    image: yunluoxincheng/yunluoblog:latest
    container_name: yunluoblog
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./uploads:/usr/share/nginx/html/uploads:ro
